
export interface Genres {
  [genre: string]: string;
}

export const shortGenreList: Genres = {
  "ambientnewage": "ambient / new age",
  "housetechno": "house / techno",
  "discoboogie": "disco / boogie",
  "postpunkwave": "post punk / new wave",
  "jazz": "jazz",
  "hiphoprandb": "hip-hop / r'n'b",
  "caribbean": "caribbean",
  "rock": "rock",

}
export const genreList: Genres = {
  "ambientnewage": "ambient / new age",
  "ambientnewage-ambient": "Ambient",
  "ambientnewage-forthworld": "Fourth World",
  "ambientnewage-kosmiche": "Kosmische",
  "ambientnewage-newage": "New Age",
  "ambientnewage-vaporwave": "Vaporwave",
  "electronicadowntempo": "electronica / downtempo",
  "electronicadowntempo-beats": "Beats",
  "electronicadowntempo-electronica": "Electronica",
  "electronicadowntempo-glitch": "Glitch",
  "electronicadowntempo-trip-hop": "Trip Hop",
  "electronicadowntempo-witch-house": "Witch House",
  "hiphoprandb": "hip-hop / r'n'b",
  "hiphoprandb-choppednscrewed": "Chopped N Screwed",
  "hiphoprandb-classichiphop": "Classic Hip Hop",
  "hiphoprandb-cloud-rap": "Cloud Rap",
  "hiphoprandb-dirtysouth": "Dirty South",
  "hiphoprandb-uk-drill": "Drill",
  "hiphoprandb-emo-rap": "Emo Rap",
  "hiphoprandb-experimentalhiphop": "Experimental Hip Hop",
  "hiphoprandb-ganstarap": "Gangsta Rap",
  "hiphoprandb-hiphop": "Hip Hop ",
  "hiphoprandb-memphis": "Memphis",
  "hiphoprandb-new-jack-swing": "New Jack Swing ",
  "hiphoprandb-rnb": "RNB",
  "hiphoprandb-rap": "Rap",
  "hiphoprandb-trap": "Trap",
  "newclub": "new club",
  "newclub-afrobeats": "Afrobeats",
  "newclub-amapiano": "Amapiano ",
  "newclub-arrocha": "Arrocha",
  "newclub-baile-funk": "Baile Funk",
  "newclub-ballroom": "Ballroom",
  "newclub-bass": "Bass",
  "newclub-batida": "Batida",
  "newclub-brega": "Brega",
  "newclub-club": "Club",
  "newclub-coupe-decale": "Coupé-Décalé",
  "newclub-deck": "Deck",
  "newclub-electro-acholi": "Electro Acholi",
  "newclub-footwork": "Footwork",
  "newclub-forro-piseiro": "Forró Piseiro",
  "newclub-gqom": "Gqom",
  "newclub-pcmusic": "Hyperpop",
  "newclub-jersey": "Jersey Club",
  "newclub-kuduro": "Kuduro",
  "newclub-kwaito": "Kwaito",
  "newclub-ndombolo": "Ndombolo",
  "newclub-nightcore": "Nightcore",
  "newclub-reggaeton": "Reggaeton",
  "newclub-singeli": "Singeli",
  "newclub-street-hop": "Street Hop",
  "newclub-vina-house": "Vina House",
  "ukdance": "uk dance / grime",
  "ukdance-bassline": "Bassline",
  "ukdance-hardcore": "Breakbeat Hardcore",
  "ukdance-donk": "Donk",
  "ukdance-drumandbass": "Drum & Bass",
  "ukdance-dubstep": "Dubstep",
  "ukdance-ukgarage": "Garage",
  "ukdance-grime": "Grime",
  "ukdance-jungle": "Jungle",
  "ukdance-speed-garage": "Speed Garage",
  "ukdance-ukfunky": "UK Funky",
  "housetechno": "house / techno",
  "housetechno-acid": "Acid",
  "housetechno-techno-ambienttechno": "Ambient Techno",
  "housetechno-house-balearichouse": "Balearic House",
  "housetechno-breaks": "Breaks",
  "housetechno-brokenbeat": "Broken Beat",
  "housetechno-house-chicagohouse": "Chicago House",
  "housetechno-house-deephouse": "Deep House",
  "housetechno-house-detroithouse": "Detroit House",
  "housetechno-techno-detroittechno": "Detroit Techno",
  "housetechno-techno-dubtechno": "Dub Techno",
  "housetechno-electro": "Electro",
  "housetechno-euro-house": "Euro House",
  "housetechno-gabba": "Gabber",
  "housetechno-ghetto-house": "Ghetto House",
  "housetechno-happy-hardcore": "Happy Hardcore",
  "housetechno-hardstyle": "Hardstyle",
  "housetechno-hip-house": "Hip-House",
  "housetechno-house": "House",
  "housetechno-house-leftfieldhouse": "Leftfield House",
  "housetechno-techno-leftfieldtechno": "Leftfield Techno",
  "housetechno-minimal": "Minimal",
  "housetechno-makina": "Mákina",
  "housetechno-tech-house": "Tech House",
  "housetechno-techno": "Techno",
  "housetechno-trance": "Trance",
  "postpunkwave": "post punk / new wave",
  "postpunkwave-ebm": "EBM",
  "postpunkwave-goth-rock": "Goth Rock",
  "postpunkwave-industrial": "Industrial ",
  "postpunkwave-minimalsynth": "Minimal Synth",
  "postpunkwave-newbeat": "New Beat",
  "postpunkwave-newwave": "New Wave",
  "postpunkwave-nowave": "No Wave",
  "postpunkwave-postpunk": "Post Punk",
  "postpunkwave-synthpop": "Synth Pop",
  "altrockpunk": "alternative rock / punk",
  "altrockpunk-artrock": "Art Rock",
  "altrockpunk-dreampop": "Dream Pop",
  "altrockpunk-emo": "Emo",
  "altrockpunk-garagerock": "Garage Rock",
  "altrockpunk-grunge": "Grunge",
  "altrockpunk-hardcore-punk": "Hardcore Punk",
  "altrockpunk-indie": "Indie Rock",
  "altrockpunk-math-rock": "Math Rock",
  "altrockpunk-noiserock": "Noise Rock",
  "altrockpunk-post-hardcore": "Post Hardcore",
  "altrockpunk-postrock": "Post Rock",
  "altrockpunk-punk": "Punk",
  "altrockpunk-shibuya-kei": "SHIBUYA-KEI",
  "altrockpunk-shoegaze": "Shoegaze",
  "rock": "rock",
  "rock-american-primitivism": "American Primitivism",
  "rock-classicrock": "Classic Rock",
  "rock-country": "Country",
  "rock-folk": "Folk",
  "rock-krautrock": "Krautrock",
  "rock-power-pop": "Power Pop",
  "rock-progrock": "Prog Rock",
  "rock-psychadelicfolk": "Psychedelic Folk",
  "rock-psychedelic-rock": "Psychedelic Rock",
  "rock-rocknroll": "Rock N Roll",
  "rock-rockabilly": "Rockabilly",
  "rock-soft-rock": "Soft Rock",
  "rock-surf": "Surf",
  "rock-yachtrock": "Yacht Rock ",
  "metal": "metal",
  "metal-blackmetal": "Black Metal",
  "metal-deathmetal": "Death Metal",
  "metal-doom": "Doom",
  "metal-grindcore": "Grindcore",
  "metal-heavymetal": "Heavy Metal ",
  "metal-metalcore": "Metalcore",
  "metal-nu-metal": "Nu Metal",
  "metal-sludge": "Sludge",
  "metal-thrash": "Thrash",
  "avantgarde": "avant garde",
  "avantgarde-darkambient": "Dark Ambient",
  "avantgarde-drone": "Drone",
  "avantgarde-experimental": "Experimental",
  "avantgarde-freakfolk": "Freak Folk",
  "avantgarde-musiqueconcrete": "Musique Concrete",
  "avantgarde-noise": "Noise",
  "caribbean": "caribbean",
  "caribbean-bashment": "Bashment",
  "caribbean-bouyon": "Bouyon",
  "caribbean-calypso": "Calypso",
  "caribbean-chutney": "Chutney",
  "caribbean-dancehall": "Dancehall",
  "caribbean-dembow": "Dembow",
  "caribbean-digi-dub": "Digi Dub",
  "caribbean-dub": "Dub",
  "caribbean-gwo-ka": "GWO KA",
  "caribbean-la-plena": "La Plena",
  "caribbean-loversrock": "Lovers Rock",
  "caribbean-mento": "Mento",
  "caribbean-raboday": "Rabòday",
  "caribbean-reggae": "Reggae",
  "caribbean-rocksteady": "Rocksteady",
  "caribbean-shatta": "Shatta",
  "caribbean-ska": "Ska",
  "caribbean-soca": "Soca",
  "caribbean-steeldrum": "Steel Drum",
  "caribbean-zouk": "Zouk",
  "latinbrazil": "latin / brazilian",
  "latinbrazil-bachata": "Bachata",
  "latinbrazil-batucada": "Batucada",
  "latinbrazil-bolero": "Bolero",
  "latinbrazil-bossanova": "Bossa Nova",
  "latinbrazil-brasillica": "Brasillica",
  "latinbrazil-champeta": "Champeta",
  "latinbrazil-corrido": "Corrido",
  "latinbrazil-cumbia": "Cumbia",
  "latinbrazil-flamenco": "Flamenco",
  "latinbrazil-forro": "Forró",
  "latinbrazil-freestyle": "Freestyle",
  "latinbrazil-guarani": "GUARANÍ",
  "latinbrazil-gaita": "Gaita",
  "latinbrazil-huaynos": "Huayños",
  "latinbrazil-joropo": "Joropo",
  "latinbrazil-kaseko": "Kaseko",
  "latinbrazil-latinjazz": "Latin Jazz",
  "latinbrazil-latin-soul": "Latin Soul",
  "latinbrazil-mariachi": "Mariachi ",
  "latinbrazil-meringue": "Meringue",
  "latinbrazil-musicapopular": "Música Popular Brasileira",
  "latinbrazil-norteno": "Norteño",
  "latinbrazil-nueva-cancion": "Nueva Cancion",
  "latinbrazil-nuevo-cancionero": "Nuevo Cancionero",
  "latinbrazil-pasillo": "Pasillo",
  "latinbrazil-quechua": "Quechua",
  "latinbrazil-rancheras": "Rancheras",
  "latinbrazil-rockola": "Rockola",
  "latinbrazil-salsa": "Salsa",
  "latinbrazil-samba": "Samba",
  "latinbrazil-tonada": "Tonada",
  "latinbrazil-zapateado": "Zapateado",
  "jazz": "jazz",
  "jazz-ambientjazz": "Ambient Jazz",
  "jazz-contemporaryjazz": "Contemporary Jazz",
  "jazz-freejazz": "Free Jazz",
  "jazz-hard-bop": "Hard Bop",
  "jazz-jazzfusion": "Jazz Fusion",
  "jazz-jazzrock": "Jazz Rock",
  "jazz-modal": "Modal",
  "jazz-post-bop": "Post Bop",
  "jazz-souljazz": "Soul Jazz",
  "jazz-spiritualjazz": "Spiritual Jazz",
  "jazz-straightjazz": "Straight Jazz",
  "jazz-sunra": "Sun Ra",
  "jazz-swing": "Swing",
  "soulrhythm": "soul / rhythm & blues",
  "soulrhythm-blues": "Blues",
  "soulrhythm-doowop": "Doo Wop",
  "soulrhythm-funk": "Funk",
  "soulrhythm-gospel": "Gospel",
  "soulrhythm-p-funk": "P Funk",
  "soulrhythm-psychedelic-soul": "Psychedelic Soul",
  "soulrhythm-raregroove": "Rare Groove",
  "soulrhythm-rhythmandblues": "Rhythm & Blues",
  "soulrhythm-sacred-harp": "Sacred Harp",
  "soulrhythm-slowjams": "Slow Jams",
  "soulrhythm-soul": "Soul",
  "soulrhythm-street-soul": "Street Soul",
  "soulrhythm-sweet-soul": "Sweet Soul",
  "discoboogie": "disco / boogie",
  "discoboogie-boogie": "Boogie",
  "discoboogie-bubblegum": "Bubblegum",
  "discoboogie-classicdisco": "Classic Disco",
  "discoboogie-cosmicdisco": "Cosmic Disco",
  "discoboogie-italo": "Italo",
  "discoboogie-leftfielddisco": "Leftfield Disco",
  "africanmiddleeast": "african / middle eastern",
  "africanmiddleeast-afrodisco": "Afro Disco",
  "africanmiddleeast-afrobeat": "Afrobeat",
  "africanmiddleeast-turkishpsych": "Anatolian Rock",
  "africanmiddleeast-arabian-bellydance": "Arabian Bellydance",
  "africanmiddleeast-arabic-pop": "Arabic Pop",
  "africanmiddleeast-arabictraditional": "Arabic Traditional",
  "africanmiddleeast-balani": "Balani",
  "africanmiddleeast-bikutsi": "Bikutsi",
  "africanmiddleeast-electroshaabi": "Chaabi",
  "africanmiddleeast-coladeira": "Coladeira",
  "africanmiddleeast-dabke": "Dabke",
  "africanmiddleeast-ethiopiques": "Ethiopiques",
  "africanmiddleeast-funana": "Funaná",
  "africanmiddleeast-ga": "Ga",
  "africanmiddleeast-gnawa": "Gnawa",
  "africanmiddleeast-griot": "Griot",
  "africanmiddleeast-halay": "Halay",
  "africanmiddleeast-highlife": "Highlife",
  "africanmiddleeast-iraqi-maqam": "Iraqi Maqam",
  "africanmiddleeast-juju": "Jùjú",
  "africanmiddleeast-khaleeji": "KHALEEJI",
  "africanmiddleeast-kalenjin": "Kalenjin",
  "africanmiddleeast-kizomba": "Kizomba",
  "africanmiddleeast-kora": "Kora",
  "africanmiddleeast-malagasy-folk": "MALAGASY FOLK",
  "africanmiddleeast-makossa": "Makossa",
  "africanmiddleeast-maloya": "Maloya",
  "africanmiddleeast-mande-music": "Mande Music",
  "africanmiddleeast-mandinka": "Mandinka",
  "africanmiddleeast-mapouka": "Mapouka",
  "africanmiddleeast-maringa": "Maringa",
  "africanmiddleeast-mbalax": "Mbalax",
  "africanmiddleeast-mizmar": "Mizmar",
  "africanmiddleeast-morna": "Morna",
  "africanmiddleeast-muzika-mizrahit": "Muzika Mizrahit",
  "africanmiddleeast-persianfolk": "Persian Traditional",
  "africanmiddleeast-qaraami": "Qaraami",
  "africanmiddleeast-rababa": "Rababa",
  "africanmiddleeast-rai": "Raï",
  "africanmiddleeast-rumba": "Rumba",
  "africanmiddleeast-saharablues": "Sahara Blues",
  "africanmiddleeast-sai": "Sai",
  "africanmiddleeast-salegy": "Salegy",
  "africanmiddleeast-semba": "Semba",
  "africanmiddleeast-shngaanelectro": "Shangaan Electro",
  "africanmiddleeast-soukous": "Soukous",
  "africanmiddleeast-south-african-jazz": "South African Jazz",
  "africanmiddleeast-sudanese-folk": "Sudanese Folk",
  "africanmiddleeast-sudanese-pop": "Sudanese Pop",
  "africanmiddleeast-sega": "Séga",
  "africanmiddleeast-taarab": "Taarab",
  "africanmiddleeast-turkishdisco": "Turkish Disco",
  "africanmiddleeast-wassalou": "Wassalou",
  "africanmiddleeast-ziglibithy": "Ziglibithy",
  "africanmiddleeast-zouglou": "Zouglou",
  "africanmiddleeast-zukra": "Zukra",
  "asia": "asia",
  "asia-luk-krung": " Luk Krung",
  "asia-baila-folk": "BAILA FOLK",
  "asia-balochi": "Balochi",
  "asia-bhangra": "Bhangra ",
  "asia-bollywood": "Bollywood",
  "asia-cpop": "C-Pop",
  "asia-canto-pop": "Canto Pop",
  "asia-chinesetraditional": "Chinese Traditional",
  "asia-choliya": "Choliya",
  "asia-cai-luong": "Cải lương",
  "asia-dangdut": "Dangdut",
  "asia-gamalan": "Gamelan",
  "asia-ghazal": "Ghazal",
  "asia-hokkien-pop": "Hokkien pop",
  "asia-indianclassical": "Indian Classical",
  "asia-jpop": "J-Pop",
  "asia-jaipong": "Jaipong",
  "asia-japanese": "Japanese Traditional",
  "asia-kpop": "K-Pop",
  "asia-keroncong": "Keroncong",
  "asia-khmer-pop": "Khmer Pop",
  "asia-korean-traditional": "Korean Traditional",
  "asia-kundiman": "Kundiman",
  "asia-kyrgyz-folk": "Kyrgyz Folk",
  "asia-lollywood": "Lollywood",
  "asia-luk-thung": "Luk Thung",
  "asia-mando-pop": "Mando Pop",
  "asia-molam": "Molam",
  "asia-nhac-vang": "Nhạc Vàng",
  "asia-pakistani-classical": "Pakistani Classical",
  "asia-pakistani-pop": "Pakistani Pop",
  "asia-pashtopop": "Pashto Pop",
  "asia-persiandisco": "Persian Pop",
  "asia-pop-sunda": "Pop Sunda",
  "asia-visual-kei": "Proto Visual Kei",
  "asia-saung": "Saung",
  "asia-shashmaqam": "Shashmaqam",
  "asia-shidaiqu": "Shidaiqu",
  "asia-tajik-folk": "Tajik Folk",
  "asia-tamil-film-music": "Tamil Film Music",
  "asia-v-pop": "V-Pop",
  "asia-vietnamese-traditional": "Vietnamese Traditional",
  "classicalopera": "classical / opera",
  "classicalopera-baroque": "Baroque",
  "classicalopera-chambermusic": "Chamber Music",
  "classicalopera-choral-music": "Choral Music",
  "classicalopera-classical": "Classical",
  "classicalopera-minimalism": "Minimalism",
  "classicalopera-modern-classical": "Modern Classical",
  "classicalopera-opera": "Opera",
  "other": "other",
  "other-australianindigenousmusic": "Australian Indigenous Music",
  "other-balkan-pop": "Balkan Pop",
  "other-bhajan": "Bhajan",
  "other-celtic-folk": "Celtic Folk",
  "other-chanson": "Chanson",
  "other-chip-tune": "Chip Tune",
  "other-christian-traditional": "Christian Traditional",
  "other-christmas": "Christmas",
  "other-dungeon-synth": "Dungeon Synth",
  "other-field-records": "Field Recordings",
  "other-greek-traditional": "Greek Traditional ",
  "other-himene-tarava": "Himene Tarava",
  "other-imene-tuki": "Imene tuki",
  "other-interview": "Interview",
  "other-irish-traditional": "Irish Traditional",
  "other-joik": "Joik",
  "other-keiji-haino-music": "Keiji Haino Music",
  "other-leftfield-pop": "Leftfield Pop",
  "other-library": "Library",
  "other-live-performance": "Live Performance",
  "other-manele-pop": "Manele pop",
  "other-nasheed": "Nasheed",
  "other-native-american-rock": "Native American Rock",
  "other-northumbrian-folk": "Northumbrian Folk",
  "other-norweigan-folk": "Norweigan Folk ",
  "other-pop": "Pop",
  "other-portugese-fado": "Portugese Fado",
  "other-qawwali": "Qawwali",
  "other-rabiz": "Rabiz",
  "other-soundtrack": "Soundtrack",
  "other-space-age-pop": "Space Age Pop",
  "other-spoken-word": "Spoken Word",
  "other-talk": "Talk",
  "sedative": "SEDATIVE",
  "the-healing-place": "The Healing Place",
  "don-t-assume": "DON’T ASSUME",
  "safe-for-work": "SAFE FOR WORK",
  "music-to-dance-to": "MUSIC TO DANCE TO",
  "maximum-effort": "MAXIMUM EFFORT",
  "nosebleed": "Nosebleed",
  "lean-back": "LEAN BACK",
  "audio-research": "AUDIO RESEARCH",
  "lsd": "LSD"
}